### PR TITLE
`dist_uncert` geographic center calculation and bug fixes

### PR DESCRIPTION
**Pull request by RowanGregoire**
`dist_uncert` now returns the latitude and longitude of the geographic center of the points it is passed. Update tests accordingly.

Fixed a bug in `dist_uncert` where calculating the distance of a point with itself would occasionally result in an `acos` domain error when the points were passed to `haversine`.

Minor changes to docstring wording.

### CODE REVIEW

**Comment by brenhinkeller** [comment]
So one tricky thing -- what do we do if we have a set of coordinates that span the date line -- like -180 latitude on one side and +180 on the other... Maybe we need some trig / modular arithmetic / etc. to help find the true center in that case?

**Comment by RowanGregoire** [comment]
Oh that's a good point - in that case it may make sense to split calculating the center into a separate function regardless of if `dist_uncert` still returns the center. Modular arithmetic seems like a solid starting point

**Comment by brenhinkeller** [comment]
Looks like this may actually be a slightly tricky problem: https://notionparallax.co.uk/2009/centroid-of-points-on-the-surface-of-a-sphere

**Comment by brenhinkeller** [comment]
Oh this looks relevant: https://skeptric.com/calculate-centroid-on-sphere/

**Comment by brenhinkeller** [comment]
I think that may be the easiest way: convert from lat-lon (and assumed radius) to cartesian coordinates, take mean in cartesian coordinates, then convert back, throw out the new r and keep the lat-lon -- (or, effectively just project the new point back to the surface of the Earth, but all that takes is keeping the new lat-lon and ignoring the new r)

**Pull request merged**
